language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt 
  - pip install coveralls
script:
  - python setup.py test
  - python -m coverage run --source asr_tools setup.py test
after_success:
  - coveralls
